### ISSUE TITLE
A giant "bug" 

### ISSUE THREAD

**Issue by FlorianRappl** [AndreasAugustin/CoffeeMind#1]
I admire your efforts, but I just realized that there is giant bug in the whole application. Just one word: CoffeeScript! :ghost: 

But its alright :hamster:

**Comment by AndreasAugustin** [comment]
:scream: 
Thank you for you words :relaxed:
The 'CoffeeScript' bug is through the whole application. But at the moment there is a nother bug with the WebStorage. And the build is also not ready yet. I try to fix it this weekend. 
The next project will be in TypeScript. Promised :alien:

**Comment by FlorianRappl** [comment]
Alright! Well done and thanks for your immediate response :alien: .
